// Auto-generated by vite-plugin-collect-icons. Do not edit.
/* eslint-disable */

export { SvgSymbolFolder } from 'app/src/components/ui/icons/symbols/all-other/06-folder';
export { SvgSymbolDot } from 'app/src/components/ui/icons/symbols/all-other/08-dot';
export { SvgSymbolOpenLink } from 'app/src/components/ui/icons/symbols/all-other/09-open-link';
export { SvgSymbolCross } from 'app/src/components/ui/icons/symbols/all-other/13-cross';
export { SvgSymbolPen } from 'app/src/components/ui/icons/symbols/all-other/14-pen';
export { SvgSymbolFormLogin } from 'app/src/components/ui/icons/symbols/all-other/15-form-login';
export { SvgSymbolFormChange } from 'app/src/components/ui/icons/symbols/all-other/16-form-change';
export { SvgSymbolClassicCheck } from 'app/src/components/ui/icons/symbols/all-other/17-checkbox-classic';
export { SvgSymbolClassicCheckEmpty } from 'app/src/components/ui/icons/symbols/all-other/18-checkbox-classic-empty';
export { SvgSymbolChevronDown } from 'app/src/components/ui/icons/symbols/all-other/20-chevron-down';
export { SvgSymbolChevronUp } from 'app/src/components/ui/icons/symbols/all-other/21-chevron-up';
export { SvgSymbolChevronDoubleDown } from 'app/src/components/ui/icons/symbols/all-other/22-chevron-double-down';
export { SvgSymbolChevronRight } from 'app/src/components/ui/icons/symbols/all-other/23-chevron-right';
export { SvgSymbolFire } from 'app/src/components/ui/icons/symbols/all-other/24-fire';
export { SvgSymbolInfo } from 'app/src/components/ui/icons/symbols/all-other/24-info';
export { SvgSymbolQuestion } from 'app/src/components/ui/icons/symbols/all-other/24-question';
export { SvgSymbolWarning } from 'app/src/components/ui/icons/symbols/all-other/24-warning';
export { SvgSymbolCode } from 'app/src/components/ui/icons/symbols/all-other/25-code';
export { SvgSymbolForms } from 'app/src/components/ui/icons/symbols/all-other/25-forms';
export { SvgSymbolEllipsis } from 'app/src/components/ui/icons/symbols/all-other/26-ellipsis';

export const collectedIconNames = ['SvgSymbolChevronDoubleDown', 'SvgSymbolChevronDown', 'SvgSymbolChevronRight', 'SvgSymbolChevronUp', 'SvgSymbolClassicCheck', 'SvgSymbolClassicCheckEmpty', 'SvgSymbolCode', 'SvgSymbolCross', 'SvgSymbolDot', 'SvgSymbolEllipsis', 'SvgSymbolFire', 'SvgSymbolFolder', 'SvgSymbolFormChange', 'SvgSymbolFormLogin', 'SvgSymbolForms', 'SvgSymbolInfo', 'SvgSymbolOpenLink', 'SvgSymbolPen', 'SvgSymbolQuestion', 'SvgSymbolWarning'] as const;
export type CollectedIconName = typeof collectedIconNames[number];