// Auto-generated by vite-plugin-collect-icons. Do not edit.
/* eslint-disable */

export { SvgSymbolFolder, SymbolFolder } from 'app/src/components/ui/icons/symbols/all-other/06-folder';
export { SvgSymbolDot, SymbolDot } from 'app/src/components/ui/icons/symbols/all-other/08-dot';
export { SvgSymbolOpenLink, SymbolOpenLink } from 'app/src/components/ui/icons/symbols/all-other/09-open-link';
export { SvgSymbolCross, SymbolCross } from 'app/src/components/ui/icons/symbols/all-other/13-cross';
export { SvgSymbolPen, SymbolPen } from 'app/src/components/ui/icons/symbols/all-other/14-pen';
export { SvgSymbolFormLogin, SymbolFormLogin } from 'app/src/components/ui/icons/symbols/all-other/15-form-login';
export { SvgSymbolFormChange, SymbolFormChange } from 'app/src/components/ui/icons/symbols/all-other/16-form-change';
export { SvgSymbolClassicCheck, SymbolCheckbox } from 'app/src/components/ui/icons/symbols/all-other/17-checkbox-classic';
export { SvgSymbolClassicCheckEmpty, SymbolCheckboxEmpty } from 'app/src/components/ui/icons/symbols/all-other/18-checkbox-classic-empty';
export { SvgSymbolChevronDown, SymbolChevronDown } from 'app/src/components/ui/icons/symbols/all-other/20-chevron-down';
export { SvgSymbolChevronUp, SymbolChevronUp } from 'app/src/components/ui/icons/symbols/all-other/21-chevron-up';
export { SvgSymbolChevronDoubleDown, SymbolDoubleDown } from 'app/src/components/ui/icons/symbols/all-other/22-chevron-double-down';
export { SvgSymbolChevronRight, SymbolChevronRight } from 'app/src/components/ui/icons/symbols/all-other/23-chevron-right';
export { SvgSymbolFire, SymbolFire } from 'app/src/components/ui/icons/symbols/all-other/24-fire';
export { SvgSymbolInfo, SymbolInfo } from 'app/src/components/ui/icons/symbols/all-other/24-info';
export { SvgSymbolQuestion, SymbolQuestion } from 'app/src/components/ui/icons/symbols/all-other/24-question';
export { SvgSymbolWarning, SymbolWarning } from 'app/src/components/ui/icons/symbols/all-other/24-warning';
export { SvgSymbolCode, SymbolCode } from 'app/src/components/ui/icons/symbols/all-other/25-code';
export { SvgSymbolForms, SymbolForms } from 'app/src/components/ui/icons/symbols/all-other/25-forms';
export { SvgSymbolEllipsis, SymbolEllipsis } from 'app/src/components/ui/icons/symbols/all-other/26-ellipsis';

export const collectedIconNames = ['SvgSymbolChevronDoubleDown', 'SvgSymbolChevronDown', 'SvgSymbolChevronRight', 'SvgSymbolChevronUp', 'SvgSymbolClassicCheck', 'SvgSymbolClassicCheckEmpty', 'SvgSymbolCode', 'SvgSymbolCross', 'SvgSymbolDot', 'SvgSymbolEllipsis', 'SvgSymbolFire', 'SvgSymbolFolder', 'SvgSymbolFormChange', 'SvgSymbolFormLogin', 'SvgSymbolForms', 'SvgSymbolInfo', 'SvgSymbolOpenLink', 'SvgSymbolPen', 'SvgSymbolQuestion', 'SvgSymbolWarning', 'SymbolCheckbox', 'SymbolCheckboxEmpty', 'SymbolChevronDown', 'SymbolChevronRight', 'SymbolChevronUp', 'SymbolCode', 'SymbolCross', 'SymbolDot', 'SymbolDoubleDown', 'SymbolEllipsis', 'SymbolFire', 'SymbolFolder', 'SymbolFormChange', 'SymbolFormLogin', 'SymbolForms', 'SymbolInfo', 'SymbolOpenLink', 'SymbolPen', 'SymbolQuestion', 'SymbolWarning'] as const;
export type CollectedIconName = typeof collectedIconNames[number];