// Auto-generated by vite-plugin-collect-icons. Do not edit.
/* eslint-disable */

// export { SvgSymbolFolder, SymbolFolder } from '../ui/icons/symbols/all-other/06-folder';
// export { SvgSymbolDot, SymbolDot } from '../ui/icons/symbols/all-other/08-dot';
// export { SvgSymbolOpenLink, SymbolOpenLink } from '../ui/icons/symbols/all-other/09-open-link';
// export { SvgSymbolCross, SymbolCross } from '../ui/icons/symbols/all-other/13-cross';
// export { SvgSymbolPen, SymbolPen } from '../ui/icons/symbols/all-other/14-pen';
// export { SvgSymbolFormLogin, SymbolFormLogin } from '../ui/icons/symbols/all-other/15-form-login';
// export { SvgSymbolFormChange, SymbolFormChange } from '../ui/icons/symbols/all-other/16-form-change';
// export { SvgSymbolClassicCheck, SymbolCheckbox } from '../ui/icons/symbols/all-other/17-checkbox-classic';
// export { SvgSymbolClassicCheckEmpty, SymbolCheckboxEmpty } from '../ui/icons/symbols/all-other/18-checkbox-classic-empty';
// export { SvgSymbolChevronDown, SymbolChevronDown } from '../ui/icons/symbols/all-other/20-chevron-down';
// export { SvgSymbolChevronUp, SymbolChevronUp } from '../ui/icons/symbols/all-other/21-chevron-up';
// export { SvgSymbolChevronDoubleDown, SymbolDoubleDown } from '../ui/icons/symbols/all-other/22-chevron-double-down';
// export { SvgSymbolChevronRight, SymbolChevronRight } from '../ui/icons/symbols/all-other/23-chevron-right';
// export { SvgSymbolFire, SymbolFire } from '../ui/icons/symbols/all-other/24-fire';
// export { SvgSymbolInfo, SymbolInfo } from '../ui/icons/symbols/all-other/24-info';
// export { SvgSymbolQuestion, SymbolQuestion } from '../ui/icons/symbols/all-other/24-question';
// export { SvgSymbolWarning, SymbolWarning } from '../ui/icons/symbols/all-other/24-warning';
// export { SvgSymbolCode, SymbolCode } from '../ui/icons/symbols/all-other/25-code';
// export { SvgSymbolForms, SymbolForms } from '../ui/icons/symbols/all-other/25-forms';
// export { SvgSymbolEllipsis, SymbolEllipsis } from '../ui/icons/symbols/all-other/26-ellipsis';

// export const collectedIconNames = ['SvgSymbolChevronDoubleDown', 'SvgSymbolChevronDown', 'SvgSymbolChevronRight', 'SvgSymbolChevronUp', 'SvgSymbolClassicCheck', 'SvgSymbolClassicCheckEmpty', 'SvgSymbolCode', 'SvgSymbolCross', 'SvgSymbolDot', 'SvgSymbolEllipsis', 'SvgSymbolFire', 'SvgSymbolFolder', 'SvgSymbolFormChange', 'SvgSymbolFormLogin', 'SvgSymbolForms', 'SvgSymbolInfo', 'SvgSymbolOpenLink', 'SvgSymbolPen', 'SvgSymbolQuestion', 'SvgSymbolWarning', 'SymbolCheckbox', 'SymbolCheckboxEmpty', 'SymbolChevronDown', 'SymbolChevronRight', 'SymbolChevronUp', 'SymbolCode', 'SymbolCross', 'SymbolDot', 'SymbolDoubleDown', 'SymbolEllipsis', 'SymbolFire', 'SymbolFolder', 'SymbolFormChange', 'SymbolFormLogin', 'SymbolForms', 'SymbolInfo', 'SymbolOpenLink', 'SymbolPen', 'SymbolQuestion', 'SymbolWarning'] as const;
// export type CollectedIconName = typeof collectedIconNames[number];
import { SvgSymbolFolder, SymbolFolder } from '../ui/icons/symbols/all-other/06-folder';
import { SvgSymbolDot, SymbolDot } from '../ui/icons/symbols/all-other/08-dot';
import { SvgSymbolOpenLink, SymbolOpenLink } from '../ui/icons/symbols/all-other/09-open-link';
import { SvgSymbolCross, SymbolCross } from '../ui/icons/symbols/all-other/13-cross';
import { SvgSymbolPen, SymbolPen } from '../ui/icons/symbols/all-other/14-pen';
import { SvgSymbolFormLogin, SymbolFormLogin } from '../ui/icons/symbols/all-other/15-form-login';
import { SvgSymbolFormChange, SymbolFormChange } from '../ui/icons/symbols/all-other/16-form-change';
import { SvgSymbolClassicCheck, SymbolCheckbox } from '../ui/icons/symbols/all-other/17-checkbox-classic';
import { SvgSymbolClassicCheckEmpty, SymbolCheckboxEmpty } from '../ui/icons/symbols/all-other/18-checkbox-classic-empty';
import { SvgSymbolChevronDown, SymbolChevronDown } from '../ui/icons/symbols/all-other/20-chevron-down';
import { SvgSymbolChevronUp, SymbolChevronUp } from '../ui/icons/symbols/all-other/21-chevron-up';
import { SvgSymbolChevronDoubleDown, SymbolDoubleDown } from '../ui/icons/symbols/all-other/22-chevron-double-down';
import { SvgSymbolChevronRight, SymbolChevronRight } from '../ui/icons/symbols/all-other/23-chevron-right';
import { SvgSymbolFire, SymbolFire } from '../ui/icons/symbols/all-other/24-fire';
import { SvgSymbolInfo, SymbolInfo } from '../ui/icons/symbols/all-other/24-info';
import { SvgSymbolQuestion, SymbolQuestion } from '../ui/icons/symbols/all-other/24-question';
import { SvgSymbolWarning, SymbolWarning } from '../ui/icons/symbols/all-other/24-warning';
import { SvgSymbolCode, SymbolCode } from '../ui/icons/symbols/all-other/25-code';
import { SvgSymbolForms, SymbolForms } from '../ui/icons/symbols/all-other/25-forms';
import { SvgSymbolEllipsis, SymbolEllipsis } from '../ui/icons/symbols/all-other/26-ellipsis';

export const collectedIconNames = ['SvgSymbolChevronDoubleDown', 'SvgSymbolChevronDown', 'SvgSymbolChevronRight', 'SvgSymbolChevronUp', 'SvgSymbolClassicCheck', 'SvgSymbolClassicCheckEmpty', 'SvgSymbolCode', 'SvgSymbolCross', 'SvgSymbolDot', 'SvgSymbolEllipsis', 'SvgSymbolFire', 'SvgSymbolFolder', 'SvgSymbolFormChange', 'SvgSymbolFormLogin', 'SvgSymbolForms', 'SvgSymbolInfo', 'SvgSymbolOpenLink', 'SvgSymbolPen', 'SvgSymbolQuestion', 'SvgSymbolWarning', 'SymbolCheckbox', 'SymbolCheckboxEmpty', 'SymbolChevronDown', 'SymbolChevronRight', 'SymbolChevronUp', 'SymbolCode', 'SymbolCross', 'SymbolDot', 'SymbolDoubleDown', 'SymbolEllipsis', 'SymbolFire', 'SymbolFolder', 'SymbolFormChange', 'SymbolFormLogin', 'SymbolForms', 'SymbolInfo', 'SymbolOpenLink', 'SymbolPen', 'SymbolQuestion', 'SymbolWarning'] as const;
export type CollectedIconName = typeof collectedIconNames[number];

export const collectedSvgSymbols = {
    SvgSymbolFolder,
    SvgSymbolDot,
    SvgSymbolOpenLink,
    SvgSymbolCross,
    SvgSymbolPen,
    SvgSymbolFormLogin,
    SvgSymbolFormChange,
    SvgSymbolClassicCheck,
    SvgSymbolClassicCheckEmpty,
    SvgSymbolChevronDown,
    SvgSymbolChevronUp,
    SvgSymbolChevronDoubleDown,
    SvgSymbolChevronRight,
    SvgSymbolFire,
    SvgSymbolInfo,
    SvgSymbolQuestion,
    SvgSymbolWarning,
    SvgSymbolCode,
    SvgSymbolForms,
    SvgSymbolEllipsis,
};

export const collectedSymbols = {
    SymbolFolder,
    SymbolDot,
    SymbolOpenLink,
    SymbolCross,
    SymbolPen,
    SymbolFormLogin,
    SymbolFormChange,
    SymbolCheckbox,
    SymbolCheckboxEmpty,
    SymbolChevronDown,
    SymbolChevronUp,
    SymbolDoubleDown,
    SymbolChevronRight,
    SymbolFire,
    SymbolInfo,
    SymbolQuestion,
    SymbolWarning,
    SymbolCode,
    SymbolForms,
    SymbolEllipsis,
};
