// Auto-generated by vite-plugin-collect-icons. Do not edit.
/* eslint-disable */

import { SvgSymbolFolder, SymbolFolder } from '../ui/icons/symbols/all-other/06-folder';
import { SvgSymbolDot, SymbolDot } from '../ui/icons/symbols/all-other/08-dot';
import { SvgSymbolOpenLink, SymbolOpenLink } from '../ui/icons/symbols/all-other/09-open-link';
import { SvgSymbolCross, SymbolCross } from '../ui/icons/symbols/all-other/13-cross';
import { SvgSymbolPen, SymbolPen } from '../ui/icons/symbols/all-other/14-pen';
import { SvgSymbolFormLogin, SymbolFormLogin } from '../ui/icons/symbols/all-other/15-form-login';
import { SvgSymbolFormChange, SymbolFormChange } from '../ui/icons/symbols/all-other/16-form-change';
import { SvgSymbolClassicCheck, SymbolCheckbox } from '../ui/icons/symbols/all-other/17-checkbox-classic';
import { SvgSymbolClassicCheckEmpty, SymbolCheckboxEmpty } from '../ui/icons/symbols/all-other/18-checkbox-classic-empty';
import { SvgSymbolChevronDown, SymbolChevronDown } from '../ui/icons/symbols/all-other/20-chevron-down';
import { SvgSymbolChevronUp, SymbolChevronUp } from '../ui/icons/symbols/all-other/21-chevron-up';
import { SvgSymbolChevronDoubleDown, SymbolDoubleDown } from '../ui/icons/symbols/all-other/22-chevron-double-down';
import { SvgSymbolChevronRight, SymbolChevronRight } from '../ui/icons/symbols/all-other/23-chevron-right';
import { SvgSymbolFire, SymbolFire } from '../ui/icons/symbols/all-other/24-fire';
import { SvgSymbolInfo, SymbolInfo } from '../ui/icons/symbols/all-other/24-info';
import { SvgSymbolQuestion, SymbolQuestion } from '../ui/icons/symbols/all-other/24-question';
import { SvgSymbolWarning, SymbolWarning } from '../ui/icons/symbols/all-other/24-warning';
import { SvgSymbolCode, SymbolCode } from '../ui/icons/symbols/all-other/25-code';
import { SvgSymbolForms, SymbolForms } from '../ui/icons/symbols/all-other/25-forms';
import { SvgSymbolEllipsis, SymbolEllipsis } from '../ui/icons/symbols/all-other/26-ellipsis';
import { SvgSymbolAppWebChrome, SymbolAppWebChrome } from '../ui/icons/symbols/app/1-app-web-chrome';
import { SvgSymbolAppWin, SymbolAppWin } from '../ui/icons/symbols/app/2-app-win';
import { SvgSymbolCatalog, SymbolCatalog } from '../ui/icons/symbols/app/3-app-fcat';
import { SvgSymbolAppWebIe, SymbolAppWebIe } from '../ui/icons/symbols/app/4-app-web-ie';
import { SvgSymbolAppWebIeText, SymbolAppWebIeText } from '../ui/icons/symbols/app/5-app-web-ie-text';
import { SvgSymbolAppWebIeDot, SymbolAppWebIeDot } from '../ui/icons/symbols/app/6-app-web-ie-dot';
import { SvgSymbolIconManualMode, SymbolManualMode } from '../ui/icons/symbols/app/7-app-manual-mode';

export * from '../ui/icons/symbols/all-other/06-folder';
export * from '../ui/icons/symbols/all-other/08-dot';
export * from '../ui/icons/symbols/all-other/09-open-link';
export * from '../ui/icons/symbols/all-other/13-cross';
export * from '../ui/icons/symbols/all-other/14-pen';
export * from '../ui/icons/symbols/all-other/15-form-login';
export * from '../ui/icons/symbols/all-other/16-form-change';
export * from '../ui/icons/symbols/all-other/17-checkbox-classic';
export * from '../ui/icons/symbols/all-other/18-checkbox-classic-empty';
export * from '../ui/icons/symbols/all-other/20-chevron-down';
export * from '../ui/icons/symbols/all-other/21-chevron-up';
export * from '../ui/icons/symbols/all-other/22-chevron-double-down';
export * from '../ui/icons/symbols/all-other/23-chevron-right';
export * from '../ui/icons/symbols/all-other/24-fire';
export * from '../ui/icons/symbols/all-other/24-info';
export * from '../ui/icons/symbols/all-other/24-question';
export * from '../ui/icons/symbols/all-other/24-warning';
export * from '../ui/icons/symbols/all-other/25-code';
export * from '../ui/icons/symbols/all-other/25-forms';
export * from '../ui/icons/symbols/all-other/26-ellipsis';
export * from '../ui/icons/symbols/app/1-app-web-chrome';
export * from '../ui/icons/symbols/app/2-app-win';
export * from '../ui/icons/symbols/app/3-app-fcat';
export * from '../ui/icons/symbols/app/4-app-web-ie';
export * from '../ui/icons/symbols/app/5-app-web-ie-text';
export * from '../ui/icons/symbols/app/6-app-web-ie-dot';
export * from '../ui/icons/symbols/app/7-app-manual-mode';

export const collectedIconComponents = [
    { component: SvgSymbolFolder,            name: 'SvgSymbolFolder',             folder: 'all-other',  sub: '06-folder' },
    { component: SymbolFolder,               name: 'SymbolFolder',                folder: 'all-other',  sub: '06-folder' },
    { component: SvgSymbolDot,               name: 'SvgSymbolDot',                folder: 'all-other',  sub: '08-dot' },
    { component: SymbolDot,                  name: 'SymbolDot',                   folder: 'all-other',  sub: '08-dot' },
    { component: SvgSymbolOpenLink,          name: 'SvgSymbolOpenLink',           folder: 'all-other',  sub: '09-open-link' },
    { component: SymbolOpenLink,             name: 'SymbolOpenLink',              folder: 'all-other',  sub: '09-open-link' },
    { component: SvgSymbolCross,             name: 'SvgSymbolCross',              folder: 'all-other',  sub: '13-cross' },
    { component: SymbolCross,                name: 'SymbolCross',                 folder: 'all-other',  sub: '13-cross' },
    { component: SvgSymbolPen,               name: 'SvgSymbolPen',                folder: 'all-other',  sub: '14-pen' },
    { component: SymbolPen,                  name: 'SymbolPen',                   folder: 'all-other',  sub: '14-pen' },
    { component: SvgSymbolFormLogin,         name: 'SvgSymbolFormLogin',          folder: 'all-other',  sub: '15-form-login' },
    { component: SymbolFormLogin,            name: 'SymbolFormLogin',             folder: 'all-other',  sub: '15-form-login' },
    { component: SvgSymbolFormChange,        name: 'SvgSymbolFormChange',         folder: 'all-other',  sub: '16-form-change' },
    { component: SymbolFormChange,           name: 'SymbolFormChange',            folder: 'all-other',  sub: '16-form-change' },
    { component: SvgSymbolClassicCheck,      name: 'SvgSymbolClassicCheck',       folder: 'all-other',  sub: '17-checkbox-classic' },
    { component: SymbolCheckbox,             name: 'SymbolCheckbox',              folder: 'all-other',  sub: '17-checkbox-classic' },
    { component: SvgSymbolClassicCheckEmpty, name: 'SvgSymbolClassicCheckEmpty',  folder: 'all-other',  sub: '18-checkbox-classic-empty' },
    { component: SymbolCheckboxEmpty,        name: 'SymbolCheckboxEmpty',         folder: 'all-other',  sub: '18-checkbox-classic-empty' },
    { component: SvgSymbolChevronDown,       name: 'SvgSymbolChevronDown',        folder: 'all-other',  sub: '20-chevron-down' },
    { component: SymbolChevronDown,          name: 'SymbolChevronDown',           folder: 'all-other',  sub: '20-chevron-down' },
    { component: SvgSymbolChevronUp,         name: 'SvgSymbolChevronUp',          folder: 'all-other',  sub: '21-chevron-up' },
    { component: SymbolChevronUp,            name: 'SymbolChevronUp',             folder: 'all-other',  sub: '21-chevron-up' },
    { component: SvgSymbolChevronDoubleDown, name: 'SvgSymbolChevronDoubleDown',  folder: 'all-other',  sub: '22-chevron-double-down' },
    { component: SymbolDoubleDown,           name: 'SymbolDoubleDown',            folder: 'all-other',  sub: '22-chevron-double-down' },
    { component: SvgSymbolChevronRight,      name: 'SvgSymbolChevronRight',       folder: 'all-other',  sub: '23-chevron-right' },
    { component: SymbolChevronRight,         name: 'SymbolChevronRight',          folder: 'all-other',  sub: '23-chevron-right' },
    { component: SvgSymbolFire,              name: 'SvgSymbolFire',               folder: 'all-other',  sub: '24-fire' },
    { component: SymbolFire,                 name: 'SymbolFire',                  folder: 'all-other',  sub: '24-fire' },
    { component: SvgSymbolInfo,              name: 'SvgSymbolInfo',               folder: 'all-other',  sub: '24-info' },
    { component: SymbolInfo,                 name: 'SymbolInfo',                  folder: 'all-other',  sub: '24-info' },
    { component: SvgSymbolQuestion,          name: 'SvgSymbolQuestion',           folder: 'all-other',  sub: '24-question' },
    { component: SymbolQuestion,             name: 'SymbolQuestion',              folder: 'all-other',  sub: '24-question' },
    { component: SvgSymbolWarning,           name: 'SvgSymbolWarning',            folder: 'all-other',  sub: '24-warning' },
    { component: SymbolWarning,              name: 'SymbolWarning',               folder: 'all-other',  sub: '24-warning' },
    { component: SvgSymbolCode,              name: 'SvgSymbolCode',               folder: 'all-other',  sub: '25-code' },
    { component: SymbolCode,                 name: 'SymbolCode',                  folder: 'all-other',  sub: '25-code' },
    { component: SvgSymbolForms,             name: 'SvgSymbolForms',              folder: 'all-other',  sub: '25-forms' },
    { component: SymbolForms,                name: 'SymbolForms',                 folder: 'all-other',  sub: '25-forms' },
    { component: SvgSymbolEllipsis,          name: 'SvgSymbolEllipsis',           folder: 'all-other',  sub: '26-ellipsis' },
    { component: SymbolEllipsis,             name: 'SymbolEllipsis',              folder: 'all-other',  sub: '26-ellipsis' },
    { component: SvgSymbolAppWebChrome,      name: 'SvgSymbolAppWebChrome',       folder: 'app',        sub: '1-app-web-chrome' },
    { component: SymbolAppWebChrome,         name: 'SymbolAppWebChrome',          folder: 'app',        sub: '1-app-web-chrome' },
    { component: SvgSymbolAppWin,            name: 'SvgSymbolAppWin',             folder: 'app',        sub: '2-app-win' },
    { component: SymbolAppWin,               name: 'SymbolAppWin',                folder: 'app',        sub: '2-app-win' },
    { component: SvgSymbolCatalog,           name: 'SvgSymbolCatalog',            folder: 'app',        sub: '3-app-fcat' },
    { component: SymbolCatalog,              name: 'SymbolCatalog',               folder: 'app',        sub: '3-app-fcat' },
    { component: SvgSymbolAppWebIe,          name: 'SvgSymbolAppWebIe',           folder: 'app',        sub: '4-app-web-ie' },
    { component: SymbolAppWebIe,             name: 'SymbolAppWebIe',              folder: 'app',        sub: '4-app-web-ie' },
    { component: SvgSymbolAppWebIeText,      name: 'SvgSymbolAppWebIeText',       folder: 'app',        sub: '5-app-web-ie-text' },
    { component: SymbolAppWebIeText,         name: 'SymbolAppWebIeText',          folder: 'app',        sub: '5-app-web-ie-text' },
    { component: SvgSymbolAppWebIeDot,       name: 'SvgSymbolAppWebIeDot',        folder: 'app',        sub: '6-app-web-ie-dot' },
    { component: SymbolAppWebIeDot,          name: 'SymbolAppWebIeDot',           folder: 'app',        sub: '6-app-web-ie-dot' },
    { component: SvgSymbolIconManualMode,    name: 'SvgSymbolIconManualMode',     folder: 'app',        sub: '7-app-manual-mode' },
    { component: SymbolManualMode,           name: 'SymbolManualMode',            folder: 'app',        sub: '7-app-manual-mode' },
];

export function DefAppTypes() {
    return (<>
        {SvgSymbolFolder()}
        {SvgSymbolDot()}
        {SvgSymbolOpenLink()}
        {SvgSymbolCross()}
        {SvgSymbolPen()}
        {SvgSymbolFormLogin()}
        {SvgSymbolFormChange()}
        {SvgSymbolClassicCheck()}
        {SvgSymbolClassicCheckEmpty()}
        {SvgSymbolChevronDown()}
        {SvgSymbolChevronUp()}
        {SvgSymbolChevronDoubleDown()}
        {SvgSymbolChevronRight()}
        {SvgSymbolFire()}
        {SvgSymbolInfo()}
        {SvgSymbolQuestion()}
        {SvgSymbolWarning()}
        {SvgSymbolCode()}
        {SvgSymbolForms()}
        {SvgSymbolEllipsis()}
        {SvgSymbolAppWebChrome()}
        {SvgSymbolAppWin()}
        {SvgSymbolCatalog()}
        {SvgSymbolAppWebIe()}
        {SvgSymbolAppWebIeText()}
        {SvgSymbolAppWebIeDot()}
        {SvgSymbolIconManualMode()}
    </>);
}
