// Auto-generated by vite-plugin-collect-icons. Do not edit.
/* eslint-disable */

import { SvgSymbolFolder, SymbolFolder } from '../ui/icons/symbols/all-other/06-folder';
import { SvgSymbolDot, SymbolDot } from '../ui/icons/symbols/all-other/08-dot';
import { SvgSymbolOpenLink, SymbolOpenLink } from '../ui/icons/symbols/all-other/09-open-link';
import { SvgSymbolCross, SymbolCross } from '../ui/icons/symbols/all-other/13-cross';
import { SvgSymbolPen, SymbolPen } from '../ui/icons/symbols/all-other/14-pen';
import { SvgSymbolFormLogin, SymbolFormLogin } from '../ui/icons/symbols/all-other/15-form-login';
import { SvgSymbolFormChange, SymbolFormChange } from '../ui/icons/symbols/all-other/16-form-change';
import { SvgSymbolClassicCheck, SymbolCheckbox } from '../ui/icons/symbols/all-other/17-checkbox-classic';
import { SvgSymbolClassicCheckEmpty, SymbolCheckboxEmpty } from '../ui/icons/symbols/all-other/18-checkbox-classic-empty';
import { SvgSymbolChevronDown, SymbolChevronDown } from '../ui/icons/symbols/all-other/20-chevron-down';
import { SvgSymbolChevronUp, SymbolChevronUp } from '../ui/icons/symbols/all-other/21-chevron-up';
import { SvgSymbolChevronDoubleDown, SymbolDoubleDown } from '../ui/icons/symbols/all-other/22-chevron-double-down';
import { SvgSymbolChevronRight, SymbolChevronRight } from '../ui/icons/symbols/all-other/23-chevron-right';
import { SvgSymbolFire, SymbolFire } from '../ui/icons/symbols/all-other/24-fire';
import { SvgSymbolInfo, SymbolInfo } from '../ui/icons/symbols/all-other/24-info';
import { SvgSymbolQuestion, SymbolQuestion } from '../ui/icons/symbols/all-other/24-question';
import { SvgSymbolWarning, SymbolWarning } from '../ui/icons/symbols/all-other/24-warning';
import { SvgSymbolCode, SymbolCode } from '../ui/icons/symbols/all-other/25-code';
import { SvgSymbolForms, SymbolForms } from '../ui/icons/symbols/all-other/25-forms';
import { SvgSymbolEllipsis, SymbolEllipsis } from '../ui/icons/symbols/all-other/26-ellipsis';
import { SvgSymbolAppWebChrome, SymbolAppWebChrome } from '../ui/icons/symbols/app/1-app-web-chrome';
import { SvgSymbolAppWin, SymbolAppWin } from '../ui/icons/symbols/app/2-app-win';
import { SvgSymbolCatalog, SymbolCatalog } from '../ui/icons/symbols/app/3-app-fcat';
import { SvgSymbolAppWebIe, SymbolAppWebIe } from '../ui/icons/symbols/app/4-app-web-ie';
import { SvgSymbolAppWebIeText, SymbolAppWebIeText } from '../ui/icons/symbols/app/5-app-web-ie-text';
import { SvgSymbolAppWebIeDot, SymbolAppWebIeDot } from '../ui/icons/symbols/app/6-app-web-ie-dot';
import { SvgSymbolIconManualMode, SymbolManualMode } from '../ui/icons/symbols/app/7-app-manual-mode';

export const collectedIconComponents = { 
    SvgSymbolAppWebChrome,
    SvgSymbolAppWebIe,
    SvgSymbolAppWebIeDot,
    SvgSymbolAppWebIeText,
    SvgSymbolAppWin,
    SvgSymbolCatalog,
    SvgSymbolChevronDoubleDown,
    SvgSymbolChevronDown,
    SvgSymbolChevronRight,
    SvgSymbolChevronUp,
    SvgSymbolClassicCheck,
    SvgSymbolClassicCheckEmpty,
    SvgSymbolCode,
    SvgSymbolCross,
    SvgSymbolDot,
    SvgSymbolEllipsis,
    SvgSymbolFire,
    SvgSymbolFolder,
    SvgSymbolFormChange,
    SvgSymbolFormLogin,
    SvgSymbolForms,
    SvgSymbolIconManualMode,
    SvgSymbolInfo,
    SvgSymbolOpenLink,
    SvgSymbolPen,
    SvgSymbolQuestion,
    SvgSymbolWarning,
    SymbolAppWebChrome,
    SymbolAppWebIe,
    SymbolAppWebIeDot,
    SymbolAppWebIeText,
    SymbolAppWin,
    SymbolCatalog,
    SymbolCheckbox,
    SymbolCheckboxEmpty,
    SymbolChevronDown,
    SymbolChevronRight,
    SymbolChevronUp,
    SymbolCode,
    SymbolCross,
    SymbolDot,
    SymbolDoubleDown,
    SymbolEllipsis,
    SymbolFire,
    SymbolFolder,
    SymbolFormChange,
    SymbolFormLogin,
    SymbolForms,
    SymbolInfo,
    SymbolManualMode,
    SymbolOpenLink,
    SymbolPen,
    SymbolQuestion,
    SymbolWarning,
};

export const collectedIconNames = [
    'SvgSymbolAppWebChrome',
    'SvgSymbolAppWebIe',
    'SvgSymbolAppWebIeDot',
    'SvgSymbolAppWebIeText',
    'SvgSymbolAppWin',
    'SvgSymbolCatalog',
    'SvgSymbolChevronDoubleDown',
    'SvgSymbolChevronDown',
    'SvgSymbolChevronRight',
    'SvgSymbolChevronUp',
    'SvgSymbolClassicCheck',
    'SvgSymbolClassicCheckEmpty',
    'SvgSymbolCode',
    'SvgSymbolCross',
    'SvgSymbolDot',
    'SvgSymbolEllipsis',
    'SvgSymbolFire',
    'SvgSymbolFolder',
    'SvgSymbolFormChange',
    'SvgSymbolFormLogin',
    'SvgSymbolForms',
    'SvgSymbolIconManualMode',
    'SvgSymbolInfo',
    'SvgSymbolOpenLink',
    'SvgSymbolPen',
    'SvgSymbolQuestion',
    'SvgSymbolWarning',
    'SymbolAppWebChrome',
    'SymbolAppWebIe',
    'SymbolAppWebIeDot',
    'SymbolAppWebIeText',
    'SymbolAppWin',
    'SymbolCatalog',
    'SymbolCheckbox',
    'SymbolCheckboxEmpty',
    'SymbolChevronDown',
    'SymbolChevronRight',
    'SymbolChevronUp',
    'SymbolCode',
    'SymbolCross',
    'SymbolDot',
    'SymbolDoubleDown',
    'SymbolEllipsis',
    'SymbolFire',
    'SymbolFolder',
    'SymbolFormChange',
    'SymbolFormLogin',
    'SymbolForms',
    'SymbolInfo',
    'SymbolManualMode',
    'SymbolOpenLink',
    'SymbolPen',
    'SymbolQuestion',
    'SymbolWarning',
] as const;

export type CollectedIconType = typeof collectedIconNames[number];